### PR TITLE
Add SSH setup link, HTTPS alternative to git clone

### PR DESCRIPTION
**Pull request by mbland**
How does this look, @wslack?

### CODE REVIEW

**Comment by wslack** [comment]
Last question: if this works for everyone, what's the benefit of the first method?

**Comment by wslack** [comment]
Also, this is a different issue, but my local server launched at 127.0.0.1:4000 - so the links didn't work. Expected?

**Comment by mbland** [comment]
Good question... lemme tweak a little more...

But 127.0.0.1:4000 and localhost:4000 are synonymous. Which links didn't work?

**Comment by wslack** [comment]
The "https://localhost:4000/" link when you click "running locally" - maybe because https?

**Comment by wslack** [comment]
Confirmed; it works now. I changed it to http://localhost:4000

**Comment by mbland** [comment]
Ah, good catch, @wslack, and thanks for fixing.

I've just kept the `https` clone in the README now, and pushed the SSH setup topic to the `GitHub setup` page.

**Comment by wslack** [comment]
Looks good! I see what you moved now.

**Pull request merged**
