### PR TITLE
"back to 18F Guides" link; link logo to 18f home

### LINKED ISSUE #17: Add a way to access the 18F Guides home page from each guide
People who are reading one guide might not know that we have other handy documents on different topics. It would be nice to have a away back to the main guide list page (https://pages.18f.gov/guides/) from any interior page of any guide, but certainly from the landing page for each guide (https://pages.18f.gov/agile/ https://pages.18f.gov/content-guide/ etc).

Perhaps it could go either in the footer, or up top under the blue header line?

The style should probably be the same as for the team page:

screen shot 2015-07-09 at 10 52 45 am

### PR DESCRIPTION
**Pull request by mbland**
Closes #17.

Suggestions for improvements?

cc: @jenniferthibault @melodykramer @blacktm @noahmanger 

The normal desktop version:

back-to-guides-desktop

The pseudo-mobile version:

back-to-guides-responsive

### CODE REVIEW

**Comment by melodykramer** [comment]
Does 'back to 18F guides' imply that they came from a guides directory? What about 'Read more 18F Guides' - implies there are more, but you didn't start from there.

**Comment by mbland** [comment]
@melodykramer I dig it. Done!

**Comment by jenniferthibault** [comment]
Nice! 
The positioning it a lil' confusing to me, since on desktop it seems to be in line with the page content (GitHub setup).

What if it were instead between the title (18F Guides Template) and the blue line? So on mobile the order would be: 
- Logo
- Title
- Read more 18F guides
- Blue line
- Nav menu
- Page content

While we're tinkering...on mobile, could we add a little more space between the logo and the page title?

**Comment by mbland** [comment]
@jenniferthibault I tried putting it between the title and the blue line, but it wasn't really looking quite right... Probably because, as I'm fond of reminding everyone, I am a backend dev. :-) But if you'd like to give it a shot...

**Comment by mbland** [comment]
OK @jenniferthibault, took a crack at it. Somehow it looks better now than it did when I tried it before:

back-to-guides-desktop-1
back-to-guides-responsive-1

**Comment by jenniferthibault** [comment]
@mbland thanks for taking a second stab! Sorry to be throwing out only suggestions here, my front-end skills are....minimal. @maya just pinged into #17 . I wonder, Maya, do you have implementation suggestions for how to  center the link vertically between the title and the blue line? Or other thoughts on positioning?

My $0.02 is that if it were able to be vertically centered here, it would be a good MVP to try out.

**Comment by maya** [comment]
@jenniferthibault I tweaked the padding a little in 7dc0ad1.

This is what it looks like on desktop:

screen shot 2015-08-10 at 8 38 03 pm

This is what it looks like on small screens:
screen shot 2015-08-10 at 8 55 22 pm

@mbland hope you don't mind me jumping into your branch!

**Comment by maya** [comment]
@jenniferthibault The link color and hover on the parent "18F Guides Template" seem a little odd. Shouldn't the base link be black to match the headlines? (update: just seeing this is the base style for links, it just looks a little odd and stands out full on bold compared to the lighter normal text styles, and still thinking the headline should be stronger and match headlines in the blacker color). Also the hover color seems like a strange light blue I haven't seen before, that I'm pretty sure doesn't pass 508 color contrast.

**Comment by jenniferthibault** [comment]
Hey @maya thank you for lending a hand!! I poked around, and the hover is #7EB8DD. Here are the contrast ratio results for #7EB8DD over white #FFFFFF http://snook.ca/technical/colour_contrast/colour.html#fg=7EB8DD,bg=FFFFFF
Not compliant. 

I've moved this over to an existing color contrast issue in #29.

**Comment by mbland** [comment]
Y'all go right ahead and jump all over this branch. Teamwork FTW! :-)

**Pull request merged**
