### PR TITLE
Use _pages collection with default permalinks

### PR DESCRIPTION
**Pull request by mbland**
Inspired by 18F/before-you-ship#54. Incorporates 18F/guides-style#26 via `guides_style_18f` v0.1.11.

@andrewmaier Once this is in, you can go ahead and pull down the changes, then work through the Guides Template before/while playing with 18F/guides-style#27.

cc: @afeld @ccostino @ertzeid

### CODE REVIEW

**Comment by ertzeid** [comment]
LGTM

**Comment by mbland** [comment]
Mind doing the honors, @ertzeid?

**Comment by mbland** [comment]
Actually, let's hold on this until 18F/guides-style#28 goes through, so I can take out the `parent:` front matter requirement as well.

**Comment by ertzeid** [comment]
Looks like the aforementioned change is merged, so merging this one now too.

**Pull request merged**
